### Ejercicio 5

Se utilizará una base de datos (en .csv) procedente de la web  [openflight](https://openflights.org/data.html) con datos de aeropuertos, estaciones de trenes y puertos de todo el mundo.
Accede a la dirección anterior y pincha en la marca señalada en amarillo para descargar los datos. Guarda el archivo en formato .csv en tu directorio de trabajo.

El dataset contiene la siguiente información:

* **AirportID**: Identificador de cada vuelo para un aeropuerto.
* **Name**: Nombre del aeropuerto.
* **City**: Ciudad en la que se encuentra el aeropuerto.
* **Country**: País o territorio en el que se encuentra el aeropuerto.
* **IATA**: Código de asociación internacional de transporte aéreo, código del aeorpuerto.
* **ICAO**: Código de organización civil internacional, código de aeoropuertto.
* **Latitude**: Coordenada del aeropuerto (latitud).
* **Longitude**: Coordenada del aeropuerto (longitud).
* **Altitude**: Altitud del aeropuerto (en pies).
* **Timezone**: Zona horaria.
* **DST**: Código referente al continente (Daylight savings time). Europe (E), A (US/CANADA), S (South America), O (Australia), Z (New Zeeland), N (None), U (Unknown).
* **Tz**: Zona horaria del aeropuerto. Por ejemplo: (America/Los_Angeles).
* **Type**: Tipo de aeropuerto: airport, station, port, unknown.
* **Source**: Fuente de datos.

**Con la información del dataset realizar lo siguiente:**
    
    
* 1 **Carga del dataset como dataframe.**

In [1]:
import pandas as pd
urlDF = 'https://github.com/jpatokal/openflights/raw/master/data/airports-extended.dat'
columnas = ['AirportID', 'Name', 'City', 'Country', 'IATA', 'ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone', 'DST', 'Tz', 'Type', 'Source']
dfAeropuertos = pd.read_csv(urlDF, header=None, names=columnas)
dfAeropuertos

,AirportID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12663,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
12664,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
12665,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.261200,-70.779198,670,\N,\N,\N,airport,OurAirports
12666,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports
12667,14111,Lincoln Train Station LNK,Lincoln,United States,\N,\N,40.815833,-96.713889,1176,-5,A,\N,\N,\N

* 2 **Muestra las primeras 10 filas del dataframe.**

In [2]:
dfAeropuertos.head(10)

,AirportID,Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,Tz,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
5,6,Wewak International Airport,Wewak,Papua New Guinea,WWK,AYWK,-3.583830,143.669006,19,10,U,Pacific/Port_Moresby,airport,OurAirports
6,7,Narsarsuaq Airport,Narssarssuaq,Greenland,UAK,BGBW,61.160500,-45.425999,112,-3,E,America/Godthab,airport,OurAirports
7,8,Godthaab / Nuuk Airport,Godthaab,Greenland,GOH,BGGH,64.190903,-51.678101,283,-3,E,America/Godthab,airport,OurAirports
8,9,Kangerlussuaq Airport,Sondrestrom,Greenland,SFJ,BGSF,67.012222,-50.711603,165,-3,E,America/Godthab,airport,OurAirports
9,10,Thule Air Base,Thule,Greenland,THU,BGTL,76.531197,-68.703201,251,-4,E,America/Thule,airport,OurAirports


* 3 **Obtén un resumen estadístico.**

In [3]:
dfAeropuertos.describe()

          AirportID      Latitude     Longitude      Altitude
count  12668.000000  12668.000000  12668.000000  12668.000000
mean    7311.584465     29.820510     -1.041145    831.871093
std     4202.520098     26.923942     83.618663   1498.239733
min        1.000000    -90.000000   -179.876999  -1266.000000
25%     3349.750000     16.115875    -77.294770     38.000000
50%     7771.500000     38.341850      6.955411    232.500000
75%    10943.250000     49.306042     47.835824    883.500000
max    14111.000000     90.000000    179.951004  14472.000000


* 4 **Para este análisis no vamos a emplear las columnas 'AirportID', 'Latitude', 'Longitude' y 'Altitude', elimínalas del dataframe.**

In [4]:
dfAeropuertos = dfAeropuertos.copy()
dfAeropuertos.drop(columns=['AirportID', 'Latitude', 'Longitude', 'Altitude'], inplace=True)

* 5 **Vuelve a obtener un resumen estadístico, ¿de qué forma han cambiado los datos?.**

In [5]:
dfAeropuertos.describe()

,Name,City,Country,IATA,ICAO,Timezone,DST,Tz,Type,Source
count,12668,12619,12668,12668,12667,12668,12668,12668,12668,12668
unique,12330,9673,241,6925,8161,42,8,312,5,4
top,North Sea,New York,United States,\N,\N,1,E,\N,airport,OurAirports
freq,21,50,2708,5744,4507,2706,3478,4282,8264,7698

* 6 **Sobre el resumen estadístico anterior parece que en la columna TZ hay un valor raro \N, revisa la proporción de los mismos con value_counts.**

In [7]:
dfAeropuertos['Tz'].value_counts()

Tz
\N                     4282
America/New_York        705
America/Chicago         402
Europe/Berlin           323
America/Anchorage       265
                       ...
Indian/Christmas          1
Indian/Cocos              1
Australia/Lord_Howe       1
Pacific/Niue              1
Europe/Andorra            1
Name: count, Length: 312, dtype: int64

* 7 **Vuelve a cargar el dataset de modo que se interpreten correctamente los valores nulos (repite el apartado 4, borra las columnas).**

In [8]:
columnas = ['AirportID', 'Name', 'City', 'Country', 'IATA', 'ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone', 'DST', 'Tz', 'Type', 'Source']
dfAeropuertos = pd.read_csv(urlDF, header=None, names=columnas, na_values='\\N')

dfAeropuertos.drop(columns=['AirportID', 'Latitude', 'Longitude', 'Altitude'], inplace=True)
dfAeropuertos

,Name,City,Country,IATA,ICAO,Timezone,DST,Tz,Type,Source
0,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,10.0,U,Pacific/Port_Moresby,airport,OurAirports
1,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,10.0,U,Pacific/Port_Moresby,airport,OurAirports
2,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,10.0,U,Pacific/Port_Moresby,airport,OurAirports
3,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,10.0,U,Pacific/Port_Moresby,airport,OurAirports
4,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,10.0,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...
12663,Ulan-Ude East Airport,Ulan Ude,Russia,NaN,XIUW,NaN,NaN,NaN,airport,OurAirports
12664,Krechevitsy Air Base,Novgorod,Russia,NaN,ULLK,NaN,NaN,NaN,airport,OurAirports
12665,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,NaN,NaN,NaN,airport,OurAirports
12666,Melitopol Air Base,Melitopol,Ukraine,NaN,UKDM,NaN,NaN,NaN,airport,OurAirports
12667,Lincoln Train Station LNK,Lincoln,United States,NaN,NaN,-5.0,A,NaN,NaN,NaN

* 8 **Diseña y desarrolla una función para revisar los value_counts de cada columna.**

In [14]:
def valueCountsColumnas(columnas):
    for columna in columnas:
        print(f"{columna}")
        print(dfAeropuertos[columna].value_counts(dropna=False))
valueCountsColumnas(dfAeropuertos.columns)

Name
Name
North Sea                       21
Train Station                   17
Ulleungdo                       13
Railway Station                 11
All Airports                    10
                                ..
Osovtsy Air Base                 1
Yuanmou Air Base                 1
Changsha Datuopu Airport/AFB     1
Xingcheng Air Base               1
Wewak International Airport      1
Name: count, Length: 12330, dtype: int64
City
City
New York            50
NaN                 49
Berlin              47
Toronto             36
Hong Kong           32
                    ..
Charlottesville      1
Bentwisch            1
Grossbrembach        1
Steigra              1
Wewak                1
Name: count, Length: 9674, dtype: int64
Country
Country
United States                  2708
Germany                         820
Canada                          640
France                          454
Australia                       445
                               ...
Niue                              1
Myanmar                           1
Wake Island                       1
Ashmore and Cartier Islands       1
Juan de Nova Island               1
Name: count, Length: 241, dtype: int64
IATA
IATA
NaN    5744
YBL       1
GIT       1
TKL       1
HZK       1
       ...
UGU       1
ETM       1
MNH       1
CGY       1
YSG       1
Name: count, Length: 6925, dtype: int64
ICAO
ICAO
NaN     4508
LCGK       1
BIPA       1
AYMH       1
AYNZ       1
        ...
ULDA       1
XIUW       1
ULLK       1
SCAT       1
HTGW       1
Name: count, Length: 8161, dtype: int64
Timezone
Timezone
 1.00     2706
-5.00     1715
 8.00      865
-6.00      808
 2.00      677
 0.00      633
 3.00      589
-8.00      471
-3.00      445
-4.00      434
 9.00      366
 NaN       353
 10.00     351
-7.00      323
-9.00      308
 7.00      254
 5.50      230
 5.00      191
 12.00     175
 4.00      131
-10.00     101
 9.50       96
 11.00      91
 3.50       81
 6.00       76
 6.50       43
 5.75       40
-1.00       26
 4.50       23
 13.00      21
-3.50       11
 8.50       10
-11.00       6
-2.00        6
-9.50        4
 12.75       2
-12.00       1
 10.50       1
 4.30        1
 5.30        1
 13.50       1
 5.45        1
Name: count, dtype: int64
DST
DST
E      3478
A      3140
U      2702
N      2154
S       474
NaN     353
O       286
Z        81
Name: count, dtype: int64
Tz
Tz
NaN                    4282
America/New_York        705
America/Chicago         402
Europe/Berlin           323
America/Anchorage       265
                       ...
Indian/Christmas          1
Indian/Cocos              1
Australia/Lord_Howe       1
Pacific/Niue              1
Europe/Andorra            1
Name: count, Length: 312, dtype: int64
Type
Type
airport    8264
NaN        1651
station    1332
unknown    1320
port        101
Name: count, dtype: int64
Source
Source
OurAirports    7698
User           3307
NaN            1651
Legacy           12
Name: count, dtype: int64

* 9 **Diseña y desarrolla una función que sobrescriba los valores nulos de las columnas IATA e ICAO por el valor 'DESCONOCIDO'. Diseñala para que te permita aceptar cualquier columna y cualquier valor a sobreescribir.**

In [17]:
def sobrescribirNulos(df, columna, valor):
    df[columna].fillna(valor, inplace=True)

sobrescribirNulos(dfAeropuertos, 'IATA', 'DESCONOCIDO')
sobrescribirNulos(dfAeropuertos, 'ICAO', 'DESCONOCIDO')
dfAeropuertos

,Name,City,Country,IATA,ICAO,Timezone,DST,Tz,Type,Source
0,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,10.0,U,Pacific/Port_Moresby,airport,OurAirports
1,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,10.0,U,Pacific/Port_Moresby,airport,OurAirports
2,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,10.0,U,Pacific/Port_Moresby,airport,OurAirports
3,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,10.0,U,Pacific/Port_Moresby,airport,OurAirports
4,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,10.0,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...
12663,Ulan-Ude East Airport,Ulan Ude,Russia,DESCONOCIDO,XIUW,NaN,NaN,NaN,airport,OurAirports
12664,Krechevitsy Air Base,Novgorod,Russia,DESCONOCIDO,ULLK,NaN,NaN,NaN,airport,OurAirports
12665,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,NaN,NaN,NaN,airport,OurAirports
12666,Melitopol Air Base,Melitopol,Ukraine,DESCONOCIDO,UKDM,NaN,NaN,NaN,airport,OurAirports
12667,Lincoln Train Station LNK,Lincoln,United States,DESCONOCIDO,DESCONOCIDO,-5.0,A,NaN,NaN,NaN

* 10 **Implementa una función que te ayude a cambiar el tipo de las variables DST y TZ como categórico. Desarrolla tu función para que te permita cambiar cualquier tipo de cualquier columna.**

In [18]:
def cambiarTipo(df, columna, tipo):
    df[columna] = df[columna].astype(tipo)

cambiarTipo(dfAeropuertos, 'DST', 'category')
cambiarTipo(dfAeropuertos, 'Tz', 'category')
dfAeropuertos.dtypes

Name          object
City          object
Country       object
IATA          object
ICAO          object
Timezone     float64
DST         category
Tz          category
Type          object
Source        object
dtype: object

* 11 **Implementa una función que te termina ver en pantalla un resumen estadístico de todas las variables categóricas.**

In [19]:
def resumenCategoricas(df):
    for columna in df.select_dtypes(include='category').columns:
        print(f"{columna}")
        print(df[columna].describe())

resumenCategoricas(dfAeropuertos)

DST
count     12315
unique        7
top           E
freq       3478
Name: DST, dtype: object
Tz
count                 8386
unique                 311
top       America/New_York
freq                   705
Name: Tz, dtype: object

* 12 **Diseña y desarrolla una función que te permita agrupar el dataframe por el tipo de aeropuerto, mostrando el conteo de los tipos. Tu función debe estar preparada para agrupar por cualquier campo.**

In [20]:
def agrupar(df, columna):
    return df.groupby(columna).size().reset_index(name='Conteo')

agrupar(dfAeropuertos, 'Type')

      Type  Conteo
0  airport    8264
1     port     101
2  station    1332
3  unknown    1320

* 13 **Selecciona el nombre de las ciudades cuyo tipo de aeropuerto sea "port".**

In [21]:
dfAeropuertos[dfAeropuertos['Type'] == 'port']['City']

6074           Macau
6438       Stockholm
6439     Helsingborg
6444        Helsinki
6565     Sakaiminato
            ...
9948       Ludington
9949       Manitowoc
10184       Shenzhen
10207          Osaka
10208        Fukuoka
Name: City, Length: 101, dtype: object

* 14 **Muestra todas las filas de los campos nombre del aeropuerto, nombre del país, nombre de la ciudad y tipo de puerto cuyo país sea Spain.**

In [22]:
dfAeropuertos[dfAeropuertos['Country'] == 'Spain'][['Name', 'Country', 'City']]

                                         Name Country                    City
1030                    Fuerteventura Airport   Spain           Fuerteventura
1031                           Hierro Airport   Spain                  Hierro
1032                         La Palma Airport   Spain  Santa Cruz De La Palma
1033                     Gran Canaria Airport   Spain            Gran Canaria
1034                        Lanzarote Airport   Spain                Arrecife
...                                       ...     ...                     ...
11437                     Madrid Estacion Sur   Spain                  Madrid
11438                     Granada Bus Station   Spain                 Granada
11879       Palma de Mallorca Cruise Terminal   Spain       Palma de Mallorca
12234                      Algeciras Heliport   Spain               Algeciras
12386  Región de Murcia International Airport   Spain                  Murcia

[145 rows x 3 columns]

* 15 **Muestra el nombre del país, del aeropuerto y tipo que sean pertenecientes de la ciudad de Madrid y Barcelona. ¿Todos los registros son de España?**

In [ ]:
dfMadridBarcelona = dfAeropuertos[(dfAeropuertos['City'] == 'Madrid') | (dfAeropuertos['City'] == 'Barcelona')][['Country', 'Name', 'Type']]
dfMadridBarcelona
# 2690	Venezuela	General José Antonio Anzoategui International ...	airport No de España

         Country                                               Name     Type
1188       Spain                    Barcelona International Airport  airport
1194       Spain                                    Getafe Air Base  airport
1198       Spain               Adolfo Suárez Madrid–Barajas Airport  airport
1214       Spain                                   Torrejón Airport  airport
1217       Spain                                     Cuatro Vientos  unknown
2690   Venezuela  General José Antonio Anzoategui International ...  airport
6302       Spain                          Barcelona Cruise Terminal  unknown
8046       Spain                                             Atocha  unknown
8053       Spain                                  Chamartin Station  station
8055       Spain                                           Aeroport  unknown
8056       Spain                                  Passeig de Gracia  unknown
8057       Spain                                              Sants  unknown
8846       Spain                                    Barajas Station  station
9156       Spain                         Aeropuerto T4 Madrid Metro  unknown
10033      Spain                                  Estacio de Franca  unknown
10264      Spain                            Placa d Espanya Station  station
10435      Spain                             Cuatro Vientos Airport  airport
11435      Spain                                    Barcelona-Sants      NaN
11437      Spain                                Madrid Estacion Sur      NaN

* 16 **Guarda los resultados anteriores en un csv llamado Madrid_Barcelona en formato csv y excel.**

In [24]:
dfMadridBarcelona.to_csv('Madrid_Barcelona.csv', index=False)
print("Archivo guardado")

Archivo guardado