---
### Ejercicio 1:

Lee los datos del fichero 'house.csv' en un dataframe. 

- ¿Hay alguna casa con 8 habitaciones?
- ¿Cual es el número mínimo y máximo de habitaciones en el DF?
- Crea una nueva columna que sea la relación de precio por planta. 

#### Solución:

In [3]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Comprobamos que haya casas con 8 habitaciones
casas8Habitaciones = df[df['bedrooms'] == 8]
print(f'Número de casas con 8 habitaciones: {len(casas8Habitaciones)}')

# Obtenemos el número minimo de habitaciones
numeroMinimoHabitaciones = df['bedrooms'].min()
print(f'Número minimo de habitaciones: {numeroMinimoHabitaciones}')

#Obtenemos el número máximo de habitaciones
numeroMaximoHabitaciones = df['bedrooms'].max()
print(f'Número máximo de habitaciones: {numeroMaximoHabitaciones}')

# Creamos la nueva columna de precio por planta
df['precioPorPlanta'] = df['price']/df['floors']
# Mostramos el dataframe para ver la nueva columna
df.head()

Número de casas con 8 habitaciones: 2
Número minimo de habitaciones: 0.0
Número máximo de habitaciones: 9.0

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country,precioPorPlanta
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA,2.086667e+05
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA,1.192000e+06
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA,3.420000e+05
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA,4.200000e+05
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA,5.500000e+05

---
### Ejercicio 2

Haciendo uso del mismo DF del ejercicio anterior calcula:
- El precio de la casa que se encuentra en la fila número 256
- El número de habitaciones de las filas 215 a 222
- Recupera una selección aleatoria del 15% del DF
- De ese 15% aleatorio, filtra aquellos registros con 3 o 4 habitaciones y precio menor a 300_000 euros

#### Solución:

In [8]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Mostramos el precio de la casa que se encuentra en la fila 256
print(f'La casa de la fila 256 tiene un precio de: {df.iloc[256]['price']}')

# Mostramos el número de habitaciones de las casas de la fila 215 hasta la 222
print('Fila:  Número Habitaciones:')
print(df.iloc[215:223]['bedrooms'])

# Obtenemos un 15% aleatorio del dataframe
df15PorCiento = df.sample(frac=0.15)
print(f'DataFrame 15%: {len(df15PorCiento)} filas')

# Filtramos el dataframe del 15% aleatorio para obtener aquellas casa con 3 o 4 habitaciones y un precio
# por debajo de los 300000
casasFiltradas = df15PorCiento[(df15PorCiento['bedrooms'].isin([3, 4])) & (df15PorCiento['price'] < 300000)]
print('Casas Filtradas: ')
casasFiltradas

La casa de la fila 256 tiene un precio de: 515000.0
Fila:  Número Habitaciones:
215    3.0
216    3.0
217    5.0
218    3.0
219    2.0
220    3.0
221    3.0
222    3.0
Name: bedrooms, dtype: float64
DataFrame 15%: 690 filas
Casas Filtradas:

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
1488,2014-05-28 00:00:00,270000.000000,3.0,1.75,1300,4127,1.0,0,0,4,650,650,1918,1953,1309 SW Webster St,Seattle,WA 98106,USA
3624,2014-06-29 00:00:00,265000.000000,3.0,1.00,1800,7650,1.0,0,0,5,1800,0,1957,0,600 Jefferson Ave NE,Renton,WA 98056,USA
363,2014-05-08 00:00:00,230000.000000,3.0,1.75,950,6000,1.0,0,0,3,790,160,1939,1969,1237 S Sullivan St,Seattle,WA 98108,USA
4367,2014-05-08 00:00:00,292285.714286,3.0,1.75,1890,13860,1.0,0,0,5,1890,0,1966,0,14405 SE 208th St,Kent,WA 98042,USA
905,2014-05-19 00:00:00,280000.000000,3.0,2.50,1720,1916,2.0,0,0,3,1720,0,2005,0,454 A St,Renton,WA 98056,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3989,2014-07-07 00:00:00,266000.000000,4.0,2.25,1995,7102,2.0,0,0,4,1995,0,1981,0,33724 27th Pl SW,Federal Way,WA 98023,USA
417,2014-05-09 00:00:00,201500.000000,3.0,1.00,1160,8320,1.0,0,0,4,1160,0,1959,0,24345 35th Pl S,Kent,WA 98032,USA
3255,2014-06-24 00:00:00,218000.000000,3.0,1.50,1330,7600,1.0,0,0,4,1330,0,1968,0,2530 SW 325th Pl,Federal Way,WA 98023,USA
319,2014-05-08 00:00:00,258000.000000,4.0,1.75,1730,8320,1.0,0,0,3,1230,500,1977,2004,30633 21st Ave SW,Federal Way,WA 98023,USA
493,2014-05-12 00:00:00,225000.000000,3.0,1.00,990,8012,1.0,0,0,4,990,0,1966,0,16411 120th Ave SE,Renton,WA 98058,USA

---
### Ejercicio 3

Genera un índice multiple con las columnas "street", "city", "statezip" y "country" bajo el nombre "localizacion", y el resto de columnas bajo el nombre "caracteristicas". Ordena dichas columnas y genera un nuevo DF que contenga solo las columnas de "localizacion".

#### Solución:

In [9]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Creamos el indice multiple
localizacion = ['street', 'city', 'statezip', 'country']

# Creamos una tupla que filtre todas las columnas del dataframe, si no pertenerce al indicie de localizacion, se agregan al
# indice de caracteristicas
tuplaIndices = [('localizacion', col) if col in localizacion else ('caracteristicas', col) for col in df.columns]

# Asignamos el multiindice a las columnas
df.columns = pd.MultiIndex.from_tuples(tuplaIndices)

# Ordenamos el dataframe
df = df.sort_index(axis=1)

# Creamos un nuevo dataframe con la columna de localizacion
dfLocalizacion = df['localizacion']

# Mostramos el dataframe
dfLocalizacion.head()

        city country  statezip                    street
0  Shoreline     USA  WA 98133      18810 Densmore Ave N
1    Seattle     USA  WA 98119           709 W Blaine St
2       Kent     USA  WA 98042  26206-26214 143rd Ave SE
3   Bellevue     USA  WA 98008           857 170th Pl NE
4    Redmond     USA  WA 98052         9105 170th Ave NE

---
### Ejercicio 4

Carga el fichero house.csv y realiza las siguientes operaciones:

- Convierte la columna 'date' en un tipo fecha.
- Genera 3 nuevas columnas fruto de extraer el año, mes y dia.
- ¿Cual es el precio medio por mes?
- Crea una nueva columna llamada **date2** fruto de sumar 20 días a la columna fecha.

#### Solución:

In [10]:
import pandas as pd

# Cargamos el fichero house.csv
df = pd.read_csv('data/house.csv')

# Convertimos el campo data a tipo fecha
df['date'] = pd.to_datetime(df['date'])

# Creamos una nueva columna para año, mes y dia
df['anio'] = df['date'].dt.year
df['mes'] = df['date'].dt.month
df['dia'] = df['date'].dt.day

# Obtenemos el precio medio por mes agrupando por la columna de mes, obteniendo la media del precio
precioMedioMes = df.groupby('mes')['price'].mean().round(2)
print(f'El precio medio por mes es: {precioMedioMes}')

# Creamos la nueva columna date2 a partir de sumar 20 dias a la columna date
df['date2'] = df['date'] + pd.Timedelta(days=20)  

# Mostramos las dos columnas de fechas
df[['date', 'date2']].head()

El precio medio por mes es: mes
5    533822.84
6    547968.18
7    614407.82
Name: price, dtype: float64

        date      date2
0 2014-05-02 2014-05-22
1 2014-05-02 2014-05-22
2 2014-05-02 2014-05-22
3 2014-05-02 2014-05-22
4 2014-05-02 2014-05-22